# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UkJpIVhY43XuZaFgs1mUPkJYoxq0hGBl
"""

import streamlit as st
import pickle
import numpy as np

model = pickle.load(open("house_price.pkl", "rb"))

st.title("🏠 House Price Prediction App")

st.write("Enter house details below:")

size = st.number_input("House Size (sqft)", min_value=200)
bedrooms = st.number_input("Number of Bedrooms", min_value=1)
bathrooms = st.number_input("Number of Bathrooms", min_value=1)
age = st.number_input("House Age (years)", min_value=0)

if st.button("Predict Price"):
    data = np.array([[size, bedrooms, bathrooms, age]])
    prediction = model.predict(data)
    st.success(f"Estimated House Price: ₦{prediction[0]:,.2f}")