# -*- coding: utf-8 -*-
"""house_model.pkl

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GPGBeOUZSBWaGvreaVCZVDdK1dczdWIW
"""

from google.colab import files
upload = files.upload()
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
house_dataset = pd.read_csv('house price prediction.csv')
import joblib
model = joblib.load("house_model.pkl")
house_dataset.head()
print(f"Shape of Data: {house_dataset.shape}")
print(f"Columns of Data: {house_dataset.columns}")
print(f"Missing value: {house_dataset.isnull().sum()}")
print(f"Duplicate: {house_dataset.duplicated().sum()}")
print(f"Data Types: {house_dataset.dtypes}")
print(f"Description: {house_dataset.describe()}")

x = house_dataset.drop('House_Price', axis=1)
y = house_dataset['House_Price']
x_train, X_test, y_train, y_test = train_test_split(x, y, random_state=0)

model = LinearRegression()
model.fit(x_train, y_train)
predictions = model.predict(X_test)

print(f"Prediction: \n {np.round(predictions, 2)}")
print(f"R2 Score: {r2_score(y_test, predictions)*100:.2f}%")