# -*- coding: utf-8 -*-
"""requirements.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hUqXNu9eO5hvssGduw2rPHhpID2ky7Y1
"""

streamlit
scikit-learn
numpy